version: "3.8"

services: 
  database:
    image: postgres:12
    environment: 
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
    volumes:
      - ./.cached/db:/var/lib/postgresql/data
    ports: 
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80